name: flutter_score_slider
description: A new Flutter Scores Slider.
version: 1.0.0
author: Applitom (Tomer Shalom) <http://applitom.com>
homepage: https://github.com/Applitom/flutter_score_slider

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
